services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./conf.d:/etc/nginx/conf.d
      # - ./certbot/www:/var/www/certbot
      # - ./certbot/conf:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot:/etc/letsencrypt
    networks:
      - web
      - internal

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi_db_user
      POSTGRES_PASSWORD: "!Asder2312"
    # ports:
    #   - "5432:5432" # Expose external
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  strapi-names:
    build: ./names-backend
    networks:
      - internal

  strapi-stocks:
    build: ./stocks-backend
    networks:
      - internal

networks:
  web:
    external: true
  internal:


volumes:
  pgdata:
