services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: always
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=rodrigodanielss@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json
    networks:
      - web-apps

  postgres:
    image: postgres:17
    container_name: postgres17
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi_db_user
      POSTGRES_PASSWORD: "!Asder2312"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web-apps

networks:
  web-apps:
    name: web-apps


volumes:
  pgdata:


  #   names-backend:
  #     build: ../names-backend
  #     profiles: [ "apps" ] # Select this group with docker compose
  #     networks:
  #       - web-apps

  #   stocks-backend:
  #     build: ../stocks-backend
  #     profiles: [ "apps" ] # Select this group with docker compose
  #     networks:
  #       - web-apps
